spring:
  application:
    name: postService
server:
  port: 8081
keycloak:
  enabled: true
  auth-server-url: http://localhost:8080
  credentials:
    secret: tbuAfRnjtQlEobZBF7dy7NApy5dlF8JE
  ssl-required: external
  realm: techbee
  resource: post_service_client
  bearer-only: true
  use-resource-role-mappings: false
logbook:
  format:
    style: http
management:
  endpoints:
    web:
      exposure:
        include: mappings
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml