apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: post-service
  name: post-service
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: post-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - image: vebstechbee03/tech-bee:post-service-latest
        imagePullPolicy: Always
        name: post-service
        ports:
        - name: liveness-port
          containerPort: 8081
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: uat
      restartPolicy: Always
      terminationGracePeriodSeconds: 30