name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          project_id: banded-pad-397603

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t post-service:latest .

      - name: Tag Docker image
        run: docker tag post-service:latest ${{ secrets.DOCKER_USERNAME }}/tech-bee:post-service-latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tech-bee:post-service-latest

      - name: Kube Tools
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          kubectl: '1.22.0'

      - name: Create kubeconfig directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials techbee-cluster --zone us-central1-c
          kubectl config use-context techbee-cluster

      - name: k8s deployment
        run: kubectl apply -f k8s/deployment.yaml